// <auto-generated />
using System;
using BankAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251002054512_UserAdded")]
    partial class UserAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountNumber");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = 1001,
                            AccountType = "Savings",
                            Balance = 6000m,
                            UserId = 1
                        },
                        new
                        {
                            AccountNumber = 1002,
                            AccountType = "Savings",
                            Balance = 7000m,
                            UserId = 2
                        },
                        new
                        {
                            AccountNumber = 1003,
                            AccountType = "Savings",
                            Balance = 8000m,
                            UserId = 3
                        },
                        new
                        {
                            AccountNumber = 1004,
                            AccountType = "Savings",
                            Balance = 9000m,
                            UserId = 4
                        },
                        new
                        {
                            AccountNumber = 1005,
                            AccountType = "Savings",
                            Balance = 10000m,
                            UserId = 5
                        },
                        new
                        {
                            AccountNumber = 1006,
                            AccountType = "Savings",
                            Balance = 11000m,
                            UserId = 6
                        },
                        new
                        {
                            AccountNumber = 1007,
                            AccountType = "Savings",
                            Balance = 12000m,
                            UserId = 7
                        },
                        new
                        {
                            AccountNumber = 1008,
                            AccountType = "Savings",
                            Balance = 13000m,
                            UserId = 8
                        },
                        new
                        {
                            AccountNumber = 1009,
                            AccountType = "Savings",
                            Balance = 14000m,
                            UserId = 9
                        },
                        new
                        {
                            AccountNumber = 1010,
                            AccountType = "Savings",
                            Balance = 15000m,
                            UserId = 10
                        },
                        new
                        {
                            AccountNumber = 1011,
                            AccountType = "Savings",
                            Balance = 16000m,
                            UserId = 11
                        },
                        new
                        {
                            AccountNumber = 1012,
                            AccountType = "Savings",
                            Balance = 17000m,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("BankAPI.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1001,
                            Amount = 6000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7607),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1002,
                            Amount = 7000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7625),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1003,
                            Amount = 8000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7628),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1004,
                            Amount = 9000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7629),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1005,
                            Amount = 10000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7654),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 1006,
                            Amount = 11000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7656),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 1007,
                            Amount = 12000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7658),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 1008,
                            Amount = 13000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7659),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 1009,
                            Amount = 14000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7662),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 1010,
                            Amount = 15000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7664),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 1011,
                            Amount = 16000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7665),
                            TransactionType = "Deposit",
                            UserId = 0
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 1012,
                            Amount = 17000m,
                            Date = new DateTime(2025, 10, 2, 13, 45, 12, 249, DateTimeKind.Local).AddTicks(7667),
                            TransactionType = "Deposit",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("BankAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Random Street",
                            Email = "fangyuan@example.com",
                            Name = "Fang Yuan",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Random Street",
                            Email = "redfog@example.com",
                            Name = "Red Fog",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Random Street",
                            Email = "blackevil@example.com",
                            Name = "Black Evil",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 4,
                            Address = "Random Street",
                            Email = "liuchen@example.com",
                            Name = "Liu Chen",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 5,
                            Address = "Random Street",
                            Email = "shenwei@example.com",
                            Name = "Shen Wei",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 6,
                            Address = "Random Street",
                            Email = "rengoku@example.com",
                            Name = "Rengoku",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 7,
                            Address = "Random Street",
                            Email = "wusheng@example.com",
                            Name = "Wu Sheng",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 8,
                            Address = "Random Street",
                            Email = "daoist@example.com",
                            Name = "Daoist",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 9,
                            Address = "Random Street",
                            Email = "masterchen@example.com",
                            Name = "Master Chen",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 10,
                            Address = "Random Street",
                            Email = "zhurong@example.com",
                            Name = "Zhu Rong",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 11,
                            Address = "Random Street",
                            Email = "limu@example.com",
                            Name = "Li Mu",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        },
                        new
                        {
                            UserId = 12,
                            Address = "Random Street",
                            Email = "yanshi@example.com",
                            Name = "Yan Shi",
                            Password = "pass123",
                            Phone = "0123456789",
                            Picture = ""
                        });
                });

            modelBuilder.Entity("BankAPI.Models.Account", b =>
                {
                    b.HasOne("BankAPI.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankAPI.Models.Transactions", b =>
                {
                    b.HasOne("BankAPI.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
